@echo off
echo 🚀 Starting CyberGuard with Performance Optimization...

echo 📦 Clearing npm cache...
npm cache clean --force >nul 2>&1

echo ⚡ Setting Node.js performance flags...
set NODE_OPTIONS=--max-old-space-size=4096 --no-experimental-fetch
set NODE_ENV=development

echo 🔥 Starting development server...
npm run dev